version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: flea_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    networks:
      - app-net

  php:
    build: ./docker/php
    container_name: flea_php
    volumes:
      - ./src:/var/www/
      - /dev/shm:/dev/shm
    env_file:
      - ./src/.env
    environment:
      DUSK_HEADLESS: "true" 
    depends_on:
      - mysql
      - mailhog
    networks:
      - app-net

  dusk:
    build: ./docker/php
    container_name: flea_dusk
    volumes:
      - ./src:/var/www/
      - /dev/shm:/dev/shm
    env_file:
      - ./src/.env.dusk.local
    environment:
      DUSK_HEADLESS: "true"
    depends_on:
      - nginx
      - mysql
      - mailhog
    networks:
      - app-net

  mysql:
    image: mysql:8.0
    container_name: flea_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init-demo_test.sql:/docker-entrypoint-initdb.d/init-demo_test.sql
    ports:
      - "3306:3306"
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: flea_phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - app-net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
